all: build
	@echo "I'm the target building and installing your files - and it's done"

build:
	@echo "Building README.md in Markdown for GitHub"
	@echo "#### ![#f03c15](https://via.placeholder.com/15/f03c15/000000?text=+) Title of Project: " > README.md
	@echo "# Week 4 Assignment: Bash, Make, Git and GitHub" >> README.md

	@echo "#### ![#66ff66](https://via.placeholder.com/15/66ff66/000000?text=+) Date and time make was run: " >> README.md
	@echo "<!-- DATE AND TIME AT WHICH MAKE WAS RUN PULLED HERE -->" >> README.md
	@echo "`date`, pulled via the UNIX date command\n" >> README.md

	@echo "#### ![#1589F0](https://via.placeholder.com/15/1589F0/000000?text=+) guessinggame.sh is this many lines long:\n" >> README.md
	@echo "<!-- NUMBER OF LINES OF CODE CALCULATED HERE -->" >> README.md
	@echo "$(shell wc -l < guessinggame.sh), pulled via (shell wc -l < guessinggame.sh)\n" >> README.md

	@echo "___\n\nThis GitHub repository only contains the following three files:\n" >> README.md
	@echo "1) A Bash script called <b>guessinggame.sh</b>, which contains:\n" >> README.md
	@echo "   ![#f03c15](https://via.placeholder.com/15/f03c15/000000?text=+) a <b>WHILE LOOP</b>\n" >> README.md
	@echo "   ![#66ff66](https://via.placeholder.com/15/66ff66/000000?text=+) a <b>FUNCTION</b> and\n" >> README.md
	@echo "   ![#1589F0](https://via.placeholder.com/15/1589F0/000000?text=+) an <b>IF STATEMENT</b>\n" >> README.md
	@echo "    and has the following behavior:\n" >> README.md
	@echo "   - [x] When the program starts the user is asked how many files are in the current directory, and is then prompted to guess\n" >> README.md
	@echo "   - [x] If the user's answer is incorrect, they are advised whether their guess is too low or too high and are prompted to guess again\n" >> README.md
	@echo "   - [x] If the user guesses correctly, they are congratulated and the program ends\n" >> README.md
	@echo "   - [x] The program doesn't end until the user has entered the correct number of files in the current directory\n" >> README.md
	@echo "   - [x] The program is run by entering <i>bash guessinggame.sh</i> into the console\n" >> README.md
	@echo "2) <b>A makefile</b>.\n" >> README.md
	@echo "3) A markdown file called <b>README.md</b>, <i>which is entirely generated by the project's makefile!</i>\n\n___\n" >> README.md
	@echo "[The Unix Workbench, Coursera](https://www.coursera.org/learn/unix)\n" >> README.md
	@echo "[Sean Hobin (GitHub)](https://github.com/AbstractMonkey)" >> README.md

clean:
	@echo "I'm the target cleaning intermediate, unnecessary files"
	rm README.md

