all: build
	@echo "I'm the target building and installing your files - and it's done"

build:
	@echo "Building README.md in Markdown for GitHub"
	@echo "# Week 4 Assignment: Bash, Make, Git and GitHub\n#### Date and time make was run: <span style=color:blue>`date`</span>\n___" >> README.md
	@echo "#### guessinggame.sh is $(shell wc -l < guessinggame.sh) lines long with 27 lines of code\n" >> README.md
	@echo "___\n\nThe GitHub repository only contains the following three files:\n\n1) A Bash script called guessinggame.sh.\n\n2) A makefile.\n\n3) A markdown file called README.md.\nThis README.md file was entirely generated by the project's makefile.\n___\n[The Unix Workbench, Coursera](https://www.coursera.org/learn/unix)\n\n[Sean Hobin (GitHub)](https://github.com/AbstractMonkey)" >> README.md

clean:
	@echo "I'm the target cleaning intermediate, unnecessary files"
	rm README.md
